reference = "4.x.x"
default = false
stable = false

platforms = ["paper"]
languages = ["java", "kotlin"]
buildTools = ["gradle", "maven"]

github = "https://github.com/TriumphTeam/triumph-gui/tree/update/v4"
