reference = "4.x.x"
default = false
stable = false

settings = [
    {
        id = "platform"
        name = "Platform"
        values = [
            {
                id = "paper"
                name = "Paper"
            }
        ]
    }
    {
        id = "language"
        name = "Language"
        values = [
            {
                id = "java"
                name = "Java"
            }
            {
                id = "kotlin"
                name = "Kotlin"
            }
        ]
    }
    {
        id = "buildtool"
        name = "Build Tool"
        values = [
            {
                id = "gradle"
                name = "Gradle"
            }
            {
                id = "maven"
                name = "Maven"
            }
        ]
    }
]

github = "https://github.com/TriumphTeam/triumph-gui/tree/update/v4"
discord = "https://discord.com/invite/mmZ6eQ6"
