conditions = [
    {
        condition = {
            id = "language"
            value = "kotlin"
        }

        value = {
            type = "file"
            identifier = "kotlin-example-example"
        }
    }
    {
        condition = {
            id = "language"
            value = "java"
        }

        value = {
            type = "file"
            identifier = "java-example-example"
        }
    }
]
