conditions = [
    {
        condition = {
            id = "language"
            value = "kotlin"
        }

        value = {
            type = "file"
            identifier = "gradle-kotlin"
        }
    }
    {
        condition = {
            id = "language"
            value = "java"
        }

        value = {
            type = "file"
            identifier = "gradle-java"
        }
    }
]
