conditions = [
    {
        condition = {
            id = "buildtool"
            value = "gradle"
        }

        value = {
            type = "file"
            identifier = "gradle"
        }
    }
    {
        condition = {
            id = "buildtool"
            value = "maven"
        }

        value = {
            type = "file"
            identifier = "maven"
        }
    }
]
