reference = "3.x.x"
default = true
stable = true

platforms = ["spigot"]
languages = ["java"]
buildTools = ["gradle", "maven"]

github = "https://github.com/TriumphTeam/triumph-gui/"
discord = "https://discord.com/invite/mmZ6eQ6"
javadocs = "https://javadoc.io/doc/dev.triumphteam/triumph-gui/"
