reference = "3.x.x"
default = true
stable = true

settings = [
    {
        id = "platform"
        name = "Platform"
        values = [
            {
                id = "bukkit"
                name = "Bukkit"
            }
        ]
    }
    {
        id = "language"
        name = "Language"
        values = [
            {
                id = "java"
                name = "Java"
            }
        ]
    }
    {
        id = "buildtool"
        name = "Build Tool"
        values = [
            {
                id = "gradle"
                name = "Gradle"
            }
            {
                id = "maven"
                name = "Maven"
            }
        ]
    }
]

github = "https://github.com/TriumphTeam/triumph-gui/"
discord = "https://discord.com/invite/mmZ6eQ6"
javadocs = "https://javadoc.io/doc/dev.triumphteam/triumph-gui/"
